version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-rishikeshdhayarkar}"
    image: cybulde-data-preparation
    platform: linux/amd64
    container_name: cybulde-data-preparation-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/gcp-101-426822-bed637fa9578.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-dhayarkar}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      - 8889:8889
      - 8000:8000

    ipc: host
    init: true