version: v3
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/morpheus-101/cybulde-data.git
dvc_data_folder: data/raw
github_user_name: morpheus-101
github_access_token_secret_id: cybulde-data-github-access-token
infrastructure:
  project_id: gcp-101-426822
  zone: us-east1-d
  network: default
dataset_reader_manager:
  _target_: cybulde.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: cybulde.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: gcp-101-426822
      gcp_github_access_token_secret_id: cybulde-data-github-access-token
      dvc_remote_repo: https://github.com/morpheus-101/cybulde-data.git
      github_user_name: morpheus-101
      version: v3
      dev_split_ratio: 0.3
    jtc:
      _target_: cybulde.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw-toxic-comment
      dataset_name: jtc
      gcp_project_id: gcp-101-426822
      gcp_github_access_token_secret_id: cybulde-data-github-access-token
      dvc_remote_repo: https://github.com/morpheus-101/cybulde-data.git
      github_user_name: morpheus-101
      version: v3
      dev_split_ratio: 0.03
    twitter:
      _target_: cybulde.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: gcp-101-426822
      gcp_github_access_token_secret_id: cybulde-data-github-access-token
      dvc_remote_repo: https://github.com/morpheus-101/cybulde-data.git
      github_user_name: morpheus-101
      version: v3
      dev_split_ratio: 0.125
      test_split_ratio: 0.1
  repartition: true
  available_memory: 3750000000.0
dataset_cleaner_manager:
  _target_: cybulde.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: cybulde.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: cybulde.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: cybulde.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: cybulde.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: cybulde.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: cybulde.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: cybulde.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: cybulde.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: cybulde.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    spell_correction:
      _target_: cybulde.data_processing.dataset_cleaners.SpellCorrectionDatasetCleaner
      spell_correction_model:
        _target_: cybulde.utils.utils.SpellCorrectionModel
        max_dictionary_edit_distance: 2
        prefix_length: 7
        count_threshold: 1
dask_cluster:
  _target_: dask_cloudprovider.gcp.GCPCluster
  n_workers: 3
  projectid: gcp-101-426822
  zone: us-east1-d
  network: default
  network_projectid: gcp-101-426822
  machine_type: e2-medium
  source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20220203
  docker_image: us-east1-docker.pkg.dev/gcp-101-426822/cyber-bul-del/cybulde-data-preparation:CF4C8646-88C5-4C9E-A09C-953FB0C283B2
  docker_args: '--log-driver=gcplogs

    '
  extra_bootstrap:
  - gcloud auth configure-docker --quiet us-east1-docker.pkg.dev
  ngpus: 0
  gpu_type: null
  filesystem_size: 50
  disk_type: pd-standard
  on_host_maintenance: MIGRATE
  worker_class: dask.distributed.Nanny
  worker_options:
    nthreads: 1
  env_vars: {}
  scheduler_options: {}
  silence_logs: null
  asynchronous: null
  security: true
  preemptible: false
  debug: false
  instance_labels: null
processed_data_save_dir: gs://rbd-mlflow/data/processed/rebalanced_splits
run_tag: rebalanced_splits
docker_image_name: us-east1-docker.pkg.dev/gcp-101-426822/cyber-bul-del/cybulde-data-preparation
docker_image_tag: CF4C8646-88C5-4C9E-A09C-953FB0C283B2
min_nrof_words: 2
